language: node_js
cache: npm
stages:
  - check
  - test
  - cov

branches:
  only:
  - master
  - /^release\/.*$/

node_js:
  - 'lts/*'
  - 'node'

os:
  - linux

script: npx nyc -s npm run test -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npm run lint

    - stage: test
      name: node
      script: npm run test

notifications:
  email: false
